[pytest]
cache_dir = ./tests/.pytest_cache
console_output_style = count
filterwarnings =
    # httpx deprecation warning.
    ignore:The 'app' shortcut is now deprecated.:DeprecationWarning
    # Pydantic deprecation warning.
    ignore:`json_encoders` is deprecated.:pydantic.PydanticDeprecatedSince20
log_auto_indent = True
log_format = %(asctime)s %(levelname)s %(message)s
log_date_format = %H:%M:%S
minversion = 7.0
testpaths = tests
